Create MVP
HannaKukhareva95/repl pull request #1
Opened 2020-10-16 13:14 UTC by HannaKukhareva95

To run the program, enter `ruby ​​run.rb` into the console. 
For a list of commands after starting the program, enter `help`.

2020-10-16 14:21 UTC, aya-soft requested changes

2020-10-16 14:21 UTC, aya-soft commented on run.rb
> +Application.new.run
А как сделать: `Application.run`?

2020-10-16 14:21 UTC, aya-soft commented on lib/commands/help.rb
> +    puts 'Commands:'
тут хотелось бы все-таки динамически показывать список. Другой программист должен как то смочь добавить в твой список твои команды ;)

2020-10-16 14:28 UTC, HannaKukhareva95 commented on run.rb
> +Application.new.run
Thanks for your comment! I will add this method, it will allow us to write this way:
```
def self.run
   new.run
end
```

2020-10-19 17:08 UTC, aya-soft requested changes

2020-10-19 17:08 UTC, aya-soft commented on lib/application.rb
> +  attr_reader :last_command, :command_manager
Please, find one that not needed ;)

2020-10-19 17:08 UTC, aya-soft commented on lib/commands/base.rb
> +    end
Let's add call method here for clarity, that raises StandardError with message "this method should be overridden in subclasses"

2020-10-19 17:08 UTC, aya-soft commented on lib/commands/help.rb
> +      puts 'Commands available'
Maube add ":" at the end to introduce the list?

2020-10-19 17:08 UTC, aya-soft commented on lib/commands/undefined.rb
> +      puts 'Invalid command, try again'
It would be nice to have ! at the end of sentence.

2020-10-22 11:34 UTC, aya-soft requested changes

2020-10-22 11:34 UTC, aya-soft commented on lib/commands/help.rb
> +      puts @command_manager.command_names
Надо по идее ридер сделать на уровне Base и без @ тут использовать название

2020-10-22 12:18 UTC, aya-soft approved these changes

2020-10-22 12:18 UTC, merged